### ISSUE TITLE
Explain Promises in JavaScript

### ISSUE THREAD

**Issue by neilchauhan2** [neilchauhan2/Learn-JavaScript#10]
Explain Promises in JavaScript, with an informative code example. Please create a separate file named JS_Promises.md.

**Comment by toryalsip** [comment]
I'd like to give this one a try.

**Comment by gyi2521** [comment]
Hello, can I work on this?

**Comment by neilchauhan2** [comment]
@gyi2521 yeah sure!

**Comment by gyi2521** [comment]
Thanks!

**Comment by gyi2521** [comment]
Hi Neil,
I was looking into this and it looks like you just closed the issue...

**Comment by neilchauhan2** [comment]
@gyi2521 Yes, I closed it just because that was an issue with the label 'hacktoberfest' and since hacktoberfest is over, I had to close it. You can still refer to the current file on Promises, and submit your PR if you have some improvements on the current version.
